# Generated by Django 6.0.3 on 2026-03-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('social', 'Social'), ('sports', 'Sports'), ('admin', 'Administration'), ('other', 'Other')], default='other', max_length=40),
        ),
    ]
