# Generated by Django 6.0.3 on 2026-03-25 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('priority', models.CharField(choices=[('standard', 'Standard'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='api.event')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('laboratory', 'Laboratory'), ('study_room', 'Study Room'), ('lecture_hall', 'Lecture Hall'), ('collab_zone', 'Collaboration Zone')], max_length=40)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.campus')),
            ],
            options={
                'ordering': ['campus', 'name'],
                'unique_together': {('campus', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('course_code', models.CharField(blank=True, max_length=40)),
                ('room', models.CharField(blank=True, max_length=120)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('enrollment_count', models.PositiveIntegerField(default=0)),
                ('audience', models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('staff', 'Staff'), ('all', 'All')], default='all', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='api.campus')),
                ('lecturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('attendees', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.resource')),
            ],
            options={
                'ordering': ['-start_time'],
                'indexes': [models.Index(fields=['resource', 'start_time', 'end_time'], name='api_booking_resourc_2fa448_idx')],
            },
        ),
    ]
