# Generated by Django 6.0.3 on 2026-03-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='university_id',
            field=models.CharField(blank=True, help_text='University email/ID for login', max_length=50, null=True, unique=True),
        ),
    ]
