# Generated by Django 6.0.3 on 2026-03-31 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('lecturer', 'Lecturer'), ('director', 'Director'), ('coordinator', 'Coordinator'), ('procurement', 'Procurement Officer'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
